language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python Search_Engine.py
after_success:
  - coverage run Search_Engine.py
  - codecov
  - bash <(curl -s https://codecov.io/bash)
